#pragma once
/* GENERATED by firmware/tools/gen_fixtures_c.py from the JSON files in testdata/payload. Do not edit. */
#include "board/board_logic.h"

typedef struct {
    const char *name;
    uint32_t age_s;   /* age of the data at display time */
    board_t board;
} fixture_t;

extern const fixture_t FIXTURES[];
extern const int FIXTURE_COUNT;

enum { FIX_LIVE, FIX_DELAYED, FIX_CANCELLED, FIX_SCHEDULED, FIX_STALE, FIX_EMPTY, FIX_PLATFORM };
