/* GENERATED by firmware/tools/gen_fixtures_c.py from the JSON files in testdata/payload. Do not edit. */
#include "fixtures/fixtures.h"

const fixture_t FIXTURES[] = {
    { .name = "live_normal", .age_s = 20, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "15:26", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "15:56", .etd = "15:56", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "16:30", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "16:59", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
    { .name = "delayed", .age_s = 45, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "15:38", .state = SVC_DELAYED, .late = 12, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "a signalling problem" },
            { .std = "15:56", .etd = "", .state = SVC_DELAYED, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "16:30", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "16:59", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
    { .name = "cancelled_platform_change", .age_s = 30, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "Mock notice: engineering work this weekend may affect services .", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "", .state = SVC_CANCELLED, .late = 0, .plat = "", .plat_was = "", .dest = "London Euston", .why = "a shortage of train crew" },
            { .std = "15:56", .etd = "15:56", .state = SVC_ON_TIME, .late = 0, .plat = "3", .plat_was = "4", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "16:30", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "16:59", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
    { .name = "scheduled_fallback", .age_s = 0, .board = {
        .mode = BOARD_SCHEDULED,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "", .state = SVC_UNKNOWN, .late = 0, .plat = "", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "15:56", .etd = "", .state = SVC_UNKNOWN, .late = 0, .plat = "", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "", .state = SVC_UNKNOWN, .late = 0, .plat = "", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "", .state = SVC_UNKNOWN, .late = 0, .plat = "", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
    { .name = "stale", .age_s = 1500, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "15:26", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "15:56", .etd = "15:56", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "16:30", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "16:59", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
    { .name = "empty", .age_s = 20, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 0,
    } },
    { .name = "platform_change_variant", .age_s = 40, .board = {
        .mode = BOARD_LIVE,
        .station = "Berkhamsted", .label = "Southbound",
        .message = "", .count = 4,
        .svc = {
            { .std = "15:26", .etd = "15:26", .state = SVC_ON_TIME, .late = 0, .plat = "3", .plat_was = "4", .dest = "London Euston", .why = "" },
            { .std = "15:56", .etd = "15:56", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:30", .etd = "16:30", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
            { .std = "16:59", .etd = "16:59", .state = SVC_ON_TIME, .late = 0, .plat = "4", .plat_was = "", .dest = "London Euston", .why = "" },
        },
    } },
};
const int FIXTURE_COUNT = 7;
