#!/usr/bin/env python3
"""Generate firmware/main/fixtures/fixtures.[ch] from testdata/payload/*.json.

On-device fixtures come from the same JSON the contract tests validate, so the panel and the
adapter cannot drift. Also derives the synthetic platform-change variant used by the takeover
design. Run: python3 firmware/tools/gen_fixtures_c.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "firmware" / "main" / "fixtures"
# name -> age in seconds at display time (matches docs/design/build_concepts.py)
FIXTURES = [("live_normal", 20), ("delayed", 45), ("cancelled_platform_change", 30),
            ("scheduled_fallback", 0), ("stale", 25 * 60), ("empty", 20)]
STATE = {"on_time": "SVC_ON_TIME", "delayed": "SVC_DELAYED", "cancelled": "SVC_CANCELLED", "unknown": "SVC_UNKNOWN"}


def c(s):
    # The panel's Montserrat has no ellipsis or en dash; keep to ASCII + Latin-1.
    s = (s or "").replace("…", "...").replace("–", "-")
    return json.dumps(s, ensure_ascii=False)


def emit(name, p, age):
    f = p["filter"]
    out = [f"    {{ .name = {c(name)}, .age_s = {age}, .board = {{",
           f"        .mode = {'BOARD_SCHEDULED' if p['mode'] == 'scheduled' else 'BOARD_LIVE'},",
           f"        .station = {c(p['station']['name'])}, .label = {c(f['label'] if f else '')},",
           f"        .message = {c(p['message'])}, .count = {len(p['services'])},"]
    if p["services"]:
        out.append("        .svc = {")
        for s in p["services"]:
            out.append(f"            {{ .std = {c(s['std'])}, .etd = {c(s['etd'])}, .state = {STATE[s['state']]}, .late = {s['late']},"
                       f" .plat = {c(s['plat'])}, .plat_was = {c(s['plat_was'])}, .dest = {c(s['dest'])}, .why = {c(s['why'])} }},")
        out.append("        },")
    out.append("    } },")
    return "\n".join(out)


def main():
    items = []
    for name, age in FIXTURES:
        items.append((name, json.loads((ROOT / "testdata" / "payload" / f"{name}.json").read_text()), age))
    plat = json.loads(json.dumps(items[0][1]))  # live_normal, next train moved to platform 3 (was 4)
    plat["services"][0].update(plat="3", plat_was="4")
    items.append(("platform_change_variant", plat, 40))

    (OUT / "fixtures.h").write_text("""#pragma once
/* GENERATED by firmware/tools/gen_fixtures_c.py from the JSON files in testdata/payload. Do not edit. */
#include "board/board_logic.h"

typedef struct {
    const char *name;
    uint32_t age_s;   /* age of the data at display time */
    board_t board;
} fixture_t;

extern const fixture_t FIXTURES[];
extern const int FIXTURE_COUNT;

enum { FIX_LIVE, FIX_DELAYED, FIX_CANCELLED, FIX_SCHEDULED, FIX_STALE, FIX_EMPTY, FIX_PLATFORM };
""")
    (OUT / "fixtures.c").write_text('/* GENERATED by firmware/tools/gen_fixtures_c.py from the JSON files in testdata/payload. Do not edit. */\n'
                                    '#include "fixtures/fixtures.h"\n\nconst fixture_t FIXTURES[] = {\n'
                                    + "\n".join(emit(*i) for i in items) + "\n};\n"
                                    f"const int FIXTURE_COUNT = {len(items)};\n")


if __name__ == "__main__":
    main()
